name: buildclient

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CI: false
      REACT_APP_RECAPTCHA_CLIENT_KEY: 6LdVxgYdAAAAAPtvjrXLAzSd2ANyzIkiSqk_yFpt
      REACT_APP_API: sb-api-fb48ef34a197.herokuapp.com
      REACT_APP_ENDPOINT_US: na.swordbattle.io
      REACT_APP_ENDPOINT_EU: swordbattle-europe-6cc6172328ee.herokuapp.com
      REACT_APP_API_BACKUP: api.swordbattle.io
      REACT_APP_ENDPOINT_US_BACKUP: swordbattlev2-42256f2058d6.herokuapp.com

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install and Build
      run: |
        cd client
        yarn install
        yarn build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./client/build
  # deploy-server:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./server
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: npm install -g @hathora/cli
  #     - run: >
  #         hathora-cloud deploy --appId app-18be24d2-4939-4030-9169-c412d9d9dc0c --token ${{ secrets.HATHORA_TOKEN }}

